#!/bin/sh

if [ $# -ne 2 ]; then
    echo "Usage: $0 <identity> <role>"
    exit 1
fi

identity=$1
role=$2
job_id=`lava-group $role`

update-ca-certificates > /dev/null 2>&1

lavacli -i $identity jobs wait --polling 60 $job_id
